name: atomsbox_models
description: A models library for Flutter developers
version: 0.1.0
repository: https://github.com/maxonflutter/atomsbox
homepage: https://atomsbox.com
documentation: https://atomsbox.com

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

