name: atomsbox
description: A curated library of pre-styled, reusable components for Flutter developers to build apps at scale
version: 0.3.0
repository: https://github.com/maxonflutter/atomsbox
homepage: https://atomsbox.com
documentation: https://atomsbox.com

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  carousel_slider: ^4.2.1
  flex_seed_scheme: ^1.2.3
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  google_fonts: ^4.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

